name: 'Terraform destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy (dev, stage, prod)'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - stage
          - prod  

jobs:
  terraform_destroy:
    name: 'Terraform destroy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2

        # this is needed because i do not have a custom docker image yet, and the docker image i use dont have az but github actions does
      - name: 'Check and install Azure CLI'
        run: |
          if ! command -v az &> /dev/null; then
            echo "Azure CLI not found, installing..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          else
            echo "Azure CLI is already installed."
          fi     

      - name: 'Azure login'
        run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password=${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Set Azure subscription'
        run: az account set --subscription 3291a0d9-96b5-41ee-9b93-5b28b419919f

      - name: 'Terraform init'
        working-directory: ./deployments
        run: terraform init

      - name: 'Select Terraform workspace'
        working-directory: ./deployments
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Create tfvars file
        run: echo "$TFVARS_CONTENT" > ./deployments/${{ inputs.environment }}.tfvars
        env:
          TFVARS_CONTENT: ${{ secrets.TFVARS_CONTENT }}
      
      - name: 'Terraform destroy'
        working-directory: ./deployments
        run: terraform destroy -auto-approve -var-file="${{ inputs.environment }}.tfvars"
      
